### ISSUE TITLE
Fix for a full screen fixed loader!

### ISSUE THREAD

**Issue by mgarcia96** [ankurk91/vue-loading-overlay#39]
Hey, use this if you want a full width container and fixed center loader:

```css
.vld-overlay .vld-icon, .vld-parent {
    position: fixed !important;
    top: 45vh !important;
}

.vld-overlay .vld-background {
    position: fixed !important;
}
```
